# Generated by Django 5.0.7 on 2024-08-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_place',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
